// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORMContext;

#nullable disable

namespace ORMContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220914122131_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ORMContext.Domain.Flight", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ArrivalAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("ORMContext.Domain.FlightHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActualStartBoaringTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdultCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AircraftSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AircraftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirlineICAOCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalculatedTakeOffTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallSign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientUniqueKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeShareInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstimatedArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstBag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FleetIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlighStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FlightId")
                        .HasColumnType("bigint");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightSuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastActionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastBag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalPaxCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPassengers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OffBlock")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OnBlock")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakeOff")
                        .HasColumnType("datetime2");

                    b.Property<string>("TakeOffFromOutStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPlannedPaxCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TouchDown")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferPaxCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransitPaxCount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightHistories");
                });

            modelBuilder.Entity("ORMContext.Domain.FlightHistory", b =>
                {
                    b.HasOne("ORMContext.Domain.Flight", "Flight")
                        .WithMany("FlightHistories")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("ORMContext.Domain.Flight", b =>
                {
                    b.Navigation("FlightHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
